### ISSUE TITLE
wrong issuer certificate

### ISSUE THREAD

**Issue by chomps1** [ebekker/ACMESharp#119] opened 2016-03-28 20:13 UTC
After installing the certificate on my server I get the following problem:
The server certificate is signed by Issuer "Let's Encrypt Authority X3". The certificate in the chain is unfortunately "Let's Encrypt Authority X1". Is this a LetsEncrypt or an ACMESharp issue?
The Powershell script for generating the certificate:
```
# set parameters
$domain = "example.com"
$certificiatePassword = "abcd1234"
$email = "info@example.com"
$vault = "D:\Vault\{0}\{1}" -f $domain, [guid]::NewGuid()
$acmechallengedir = "C:\inetpub\wwwroot\.well-known\acme-challenge\"

# include ACMEsharp
Set-ExecutionPolicy Unrestricted
Import-Module ACMEsharp.psd1

# make dir vault
mkdir $vault
d:
cd $vault

# initialize ACMEVault
Initialize-ACMEVault -force -BaseURI https://acme-v01.api.letsencrypt.org/directory
New-ACMERegistration -Contacts mailto:$email -AcceptTos

New-ACMEIdentifier -Dns $domain -Alias dns1
$completedChallenge = Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler manual
$challengeAnswer = ($completedChallenge.Challenges | Where-Object { $_.Type -eq "http-01" }).Challenge

# save token to file
$challengeFile =  $acmechallengedir + $challengeAnswer.Token
$challengeContent = $challengeAnswer.FileContent
[System.IO.File]::WriteAllText($challengeFile, $challengeContent)

# submit challenge
$challenge = Submit-ACMEChallenge -Ref dns1 -Challenge http-01
Write-Host $challenge
While ($challenge.Status -eq "pending") {
  Start-Sleep -m 500 # wait half a second before trying
  Write-Host "Status is still 'pending', waiting for it to change..."
  $challenge = Update-ACMEIdentifier -Ref dns1
  Write-Host $challenge
}

#get certificate
New-ACMECertificate -Identifier dns1 -Alias cert1 -Generate
$certificateInfo = Submit-ACMECertificate -Ref cert1
While([string]::IsNullOrEmpty($certificateInfo.IssuerSerialNumber)) {
 Start-Sleep -m 500 # wait half a second before trying
 Write-Host "IssuerSerialNumber is not set yet, waiting for it to be populated..."
 $certificateInfo = Update-ACMECertificate -Ref cert1
}
$CertFile = $vault + "\cert1-all.pfx"
Get-ACMECertificate -Ref cert1 -ExportPkcs12 $CertFile -CertificatePassword $certificiatePassword

#install certificate
certutil -p $certificiatePassword -importpfx $CertFile

Write-Host "All done, there's a cert1-all.pfx file in $vault with password $certificiatePassword"
Write-Host "Import of certificate is completed"
```_

**Comment by sjkp** [comment] 2016-03-28 20:27
I have asked on the lets encrypt forum. https://community.letsencrypt.org/t/certificates-issued-by-lets-encrypt-authority-x3-not-valid-in-mozilla/13320 

Im not an expert on the topic. But as I can see, the code that generates the pfx file, is supplied with the certificate response from the ACME server (which does use the X1 intermediate, while the issuer certifacte is in fact an X3) How the output of the export is supposed to look it don't know. 
```
var certs = new[] { crt, isu };
cp.ExportArchive(pk, certs, ArchiveFormat.PKCS12, fs, password); 
```

**Comment by bseddon** [comment] 2016-03-28 23:39
If ACMESharp is using Let's Encrypt Authority X1 to create the pfx and Let's Encrypt now uses Let's Encrypt Authority X3 (they have threatened to for a while) then you can download the X3 intermediate certificate and import it into your certificate store. The LE certificates are available here: https://letsencrypt.org/certificates/

Once the X3 certificate is in your certificate store you don't need to use the PKCS12 option. Just export the certificate and import it alone.

It's my experience that unless the X1 (or X3) certificate is in the Windows certificate store, the option to export a pfx file does not work.

**Comment by webprofusion-chrisc** [comment] 2016-03-29 03:53
Here's an analysis example for one of my sites: https://www.ssllabs.com/ssltest/analyze.html?d=apetools.webprofusion.com

I'm confused as to where the responsibility for getting this to work (fixing the incomplete certificate chain) would lie? Obviously we want to avoid much manual handling of certificate files.

**Comment by sjkp** [comment] 2016-03-29 06:52
If I have both X1 and X3 in my intermediate certificate store on windows
![image](https://cloud.githubusercontent.com/assets/3397744/14100125/5a2554be-f58b-11e5-9312-878296b26f39.png)
Then the chain looks like this
![image](https://cloud.githubusercontent.com/assets/3397744/14100132/669e04ac-f58b-11e5-897d-5325147add87.png)

If I uninstall X1 from the intermediate store, 
then the chain looks like this
![image](https://cloud.githubusercontent.com/assets/3397744/14100146/843ce5e6-f58b-11e5-9f0a-7c8051dbbcaf.png)
 
I'm not a cert expert, but is this how it is supposed to work?

**Comment by webprofusion-chrisc** [comment] 2016-03-29 08:20
That's interesting, does that have any bearing on the public cert chain if you then analyse with ssllabs.com? The question for me is does this just affect existing users or will new users see the same issue.

**Comment by webprofusion-chrisc** [comment] 2016-03-29 08:22
Oh, and the reason this is important is that some browsers think its ok-ish to have a wonky cert chain but Firefox errors outright.

**Comment by sjkp** [comment] 2016-03-29 09:22
Firefox relies on the intermediate certs being served by the webserver afaik as it have its own cert store (it does work in firefox if you manually add the x3 cert to the store). Whereas chrome/ie er uses certs from windows cert store.

**Comment by chomps1** [comment] 2016-03-29 09:59
I had to remove the X1 Cert and added the X3 Cert. Now, the chain is valid also for Firefox. Still, I don't understand why MS Server mix up the two certificates (X1/X3).

**Comment by bseddon** [comment] 2016-03-29 10:18
I've just been through the proccess to (re)generate a certificate for my test site (https://wordpress.wproute.com/).  It has been generated by Let's Encrypt using the LE X3 intermediary certificate.  

My take away is that the certificate only works if the LE X3 certificate is the only LE intermediary certificate in the Intermediate Certificate store.  When this is the case, I see a clean report by https://www.ssllabs.com

https://www.ssllabs.com/ssltest/analyze.html?d=wordpress.wproute.com

When both the X1 and X3 certificates are in the intermediate certificate store, the report shows a problem that the X3 certificate is missing.  This is the same error as reported by @webprofusion-chrisc above.

The solution seems to be to remove the X1 certificate.  However for me, it was not quite this simple.  To have the site appear correctly in FireFox (no warning message) it was necessary to edit the HTTPS site binding in IIS and re-add the certificate to the site.  Without this step, IIS served the X1 certificate to FireFox which, as has been reported, cause FireFox to complain.

Since this is a problem for me because some of my existing certificates rely on the X1 intermediate certificate.  Because it is ideal that only the X3 certificate exists in the intermediate certificate store, I will regenerate all my certificates which should solve the problem.

**Comment by flaax** [comment] 2016-03-29 17:56
I've got the same problem in IIS 8.0 / Windows Server 2012. Unfortunately I didn't make it to resolve the problem by deleting the X1 intermediate from certlm.

Things I've tried so far:

- removed all old certificates issued mid january (X1 authority) from IIS and local machine cert store, removed all LE intermediates (double and tripple checked), removed DST Root CA from LM cert store
- issue new certificates (all X3) and install automatically
- manually install DST Root CA and LE X3 intermediate
- export all certificates, cleaning cert store again and installing certs manually
- break down issued .pfx into key and cert, add X3 and DST root CA and create new pfx with full chain
- installed all LE intermediates - Windows / IIS is picking X1 automatically
- installed LE intermediate that was offered by ssllabs.com
- I've even tried the ISRG Root X1 and ISRG X1 authority (ofc issuer doesn't fit)
every time with cleaning cert store, reassign certs to bindings in IIS and make sure everything is complete and fine

Nothing helped and it's driving me crazy. I don't have any idea what I am missing since it cannot be that hard and other certificates (not from LE) are all working fine, even in Firefox.

https://www.ssllabs.com/ssltest/analyze.html?d=www.flaax.eu

The fist LE certificates I've issued were fine in all browsers in mid january (X1 intermediate & issuer). I've installed further certificates two days ago and noticed the new X3 and the problems with the "missing intermediate" and firefox.

**Comment by sjkp** [comment] 2016-03-29 18:37
@flaax did you reselect the cert in iis and save it again. I read about people having issues with changes not being applied until they change the cert in iis even if it is to the same cert.

**Comment by sjkp** [comment] 2016-03-30 05:17
@chomps1 I can confirm what you are saying, the new issued SSL certs also have
X509v3 Authority Key Identifier:
    keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

Which windows cert store probably uses to build the chain, and when two certs with the same identifier exists it seems like it just picks the first.

**Comment by webprofusion-chrisc** [comment] 2016-03-30 05:30
I can confirm that removing the X1 certificate from Certificate Manager > Intermediate Certification Authorities > Certificates fixes this issue in Firefox but invalidates any old certs issued before the switch to X3.

After removing X1 and re-requesting a certificate for an existing site I had to remove the existing identifier from the ACMESharp Vault (my Certify app does this with a right-click on the domain identifier) before requesting the certificate again, otherwise it was still associated with X1 instead of X3 (I'm guessing cached assets in the vault?).

**Comment by bseddon** [comment] 2016-03-30 08:08
Yes.  When you 'generate' a certificate using an existing identifier (alias) you are just copying the existing license out of the vault.  If you look in the vault folder there are sub-folders.  These folder contain copies of the various bits of information held on the LE servers about your identifier, including the generated certificate. So all ACMESharp is doing is copying the existing license out of one of the folders.

If you want to generate a completely new license always use a new alias.

**Comment by some-guy-23** [comment] 2016-03-30 15:04
On Windows, make sure you remove the X1 intermediate cert from both LM _and _User stores. Once I did that, all my certs paths then used X3.

**Comment by sjkp** [comment] 2016-04-04 12:26
@some-guy-23 did you find a fix?

**Comment by webprofusion-chrisc** [comment] 2016-04-04 13:47
Try re-requesting the certificate after deleting/renaming your original vault folder. This removes the possibility of cached assets being used to construct your final pfx.

**Comment by some-guy-23** [comment] 2016-04-04 14:45
@sjkp - nope, I'm pretty much stuck!

@webprofusion-chrisc - this is actually one of the things I tried, since I had to update all the X1 issued certs to X3 issued anyhow.

**Comment by Trapulo** [comment] 2016-04-06 15:49
Same issue after updated some existing certificates, now signed by the stupid "X3 using same key as X1" authority. Tried to install the X3 in cert store, remove the X1, reboot, etc. but still IIS do not chain right and FFOX do not open web sites.

**Comment by bseddon** [comment] 2016-04-06 17:26
I'm also using IIS 8.5 and I don't see the issue if I remove the X1 certificate.  As I noted above, I found it was necessary to refresh the bindings by, for example, removing the certificate and then reapply it to a site.

**Comment by some-guy-23** [comment] 2016-04-06 17:27
@bseddon - Can you run this OpenSSL test from a client machine, to your server? Does everything pass?

openssl s_client -connect {server.com}:443 -servername {domain.server.com}

Here are a list of sites hosting binaries for Windows if you need them for OpenSSL - https://wiki.openssl.org/index.php/Binaries

**Comment by bseddon** [comment] 2016-04-06 17:41
I'm not going to install openssl but here is a screenshot of the output of using https://www.ssllabs.com on my site after the X1 certificate has been removed.  You will see that the X3 certificate is used, that there is not problem (if the X1 certificate is installed it reports that not all certificates are available).  If you scroll to the the end the output confirms I'm using IIS 8.5.

I removed the X1 certificate just for the purpose of this post.  By the time you read this it will be back in place so you will be able to confirm there is a problem when it it there.

![image](https://cloud.githubusercontent.com/assets/1221824/14326566/8566968c-fc26-11e5-8270-17372a16209c.png)

**Comment by some-guy-23** [comment] 2016-04-06 17:55
Thanks for that @bseddon, I just ran the SSL Labs test on my server as well, and got the error of -

> Chain issues	Incomplete, Extra certs

It shows the X3 intermediate as being in the certification path, but an "extra download". Looks like it is the same error your site is generating after you put the X1 cert back, is this the same error that you originally got, before removing the X1 cert?

So, I guess the issue is, for some reason my server is still distributing the X1 intermediate certificate, even though it is nowhere in the cert store, and the server has been rebooted. Some clients/browsers will use this cert, and be happy with it, ignoring the X3 intermediate. Others will use the X1 cert, and throw an error, because it isn't the correct name. Finally, some will actually correctly use the X3 intermediate, even though the X1 is also being served (Firefox seems to be doing this for me).

**Comment by RvdHout** [comment] 2016-04-07 10:33
Cleaned up the whole certificate store, reinstalled all certificates ans still IIS (8.x) serves the X1 cert to clients, i'm clueless how to proceed now :(

**Comment by bseddon** [comment] 2016-04-07 11:52
@some-guy-23 Yes, that's the same error. You will see the same error now on the site shown in being used in the screen shot above because I've added the X1 certificate.

By definition (and this comment also applies to @RvdHout) the certificate is in your store. You may not be able to see it but IIS can. IIS is not going to manufacture a certificate that you have explicitly removed.

Just for the record, the only place the LE certificates appears on my server is in the intermediate certificate store of the computer.

But let me check with you. After you have removed the X1 certificate, have you removed and re-added the binding for port 443 (HTTPS) for the site you are using?  I found that unless I did this (or selected a different certificate, saved, and then selected the LE certificate again) the certificate path was still not correct.  It seems like IIS is caching the certificate or at least a reference to it.

**Comment by some-guy-23** [comment] 2016-04-07 14:47
@bseddon - yeap, I've removed the bindings completely, and redone then, to no avail. Have also created a whole new site in IIS in attempt to fix the issue, but it still serves out the X1 cert.

As you say, the X1 cert has to be somewhere, it can't just manufacturer it out of thin air, I'm just not sure where...

**Comment by Trapulo** [comment] 2016-04-07 14:51
Same test. Removed X1 (I cannot find references) and requested a new cert from LE. In win store I can open the new cert and it report as chain the X3 intermediate. Also OLD certificates report "issued by X1" but the chain reports "X3 intermediate, I think because X1 and X3 have same key. So win is resolving all to X3.

Still, IIS is serving pages using X1 as intermediate, both on old and new certificates.

**Comment by bseddon** [comment] 2016-04-07 15:03
How about checking the certificate store using PowerShell?  The MMC snapin view is not always the same as the PowerShell view.  For example, in the command line view, there is no distinction between the root certificates and intermediate certificates, they all show in the 'CA' store.  You should be able to use the 'cert' scheme to explore the store at a PowerShell command prompt.  For example:

```
dir Cert:\LocalMachine\CA
```

```
dir Cert:\LocalMachine\WebHosting
```

**Comment by some-guy-23** [comment] 2016-04-07 15:09
@bseddon - ran the powershell commands, first one shows my X3 certificate. The second shows all my site certs, so basically as expected. No X1 cert to be found.

**Comment by Trapulo** [comment] 2016-04-07 15:13
me too

**Comment by RvdHout** [comment] 2016-04-07 15:13
Same here :(

**Comment by bseddon** [comment] 2016-04-07 15:28
You have my condolences.

Although this post references IIS 7 could the basic scenario apply to you?

http://serverfault.com/questions/320495/iis-7-still-serving-old-ssl-certificate

The questioner found that the IIS instance being updated to use a new certificate was in fact behind another server and the other server was issuing an older certificate (not LE but the principle could still be relevant).

**Comment by some-guy-23** [comment] 2016-04-13 14:58
Someone finally found a working solution! (that doesn't require wiping the entire machine) -

https://community.letsencrypt.org/t/iis-8-5-building-incorrect-chain-with-lets-encrypt-authority-x3/13320/84?u=some-guy-23

Turns out there is another, normally not accessible, cert store!

**Comment by RvdHout** [comment] 2016-04-13 15:00
That solution by Knagis works for me!

**Comment by Trapulo** [comment] 2016-04-13 15:08
as I wrote in #177, also for me...

quite strange that old certificates, issued by X1, still work an browsers see X1 in the chain. I will reissue them ASAP...

**Comment by ebekker** [comment] 2016-04-20 20:33
Is the fix described by Knagis working for everyone?

**Comment by flaax** [comment] 2016-04-22 07:08
> Is the fix described by Knagis working for everyone?

It worked for me too.
The X1 intermediate cert (and only the x1 cert) was still in the local system cert store. (Why the hell is there such a thing... and how did the intermediate cert get there)
I've removed the bindings from the sites in IIS, exported the domain certificates, deleted the certs from local machine (certlm) and personal (certmgr) cert stores, deleted the old cert from the local system store as described by Knagis, installed the domain certificates again, set the bindings and it worked as it should be. No need to restart Windows Server or the IIS service. The server is sending the correct intermediate cert now.

Thank you guys for all the support in this place too!

**Comment by jocool** [comment] 2016-04-28 09:21
Same for me, Knagis saved my day :)

**Comment by japi** [comment] 2016-06-13 14:23
Is there any valid reason to use the same key identifier twice?
Why did LetsEncrypt do that? :-(
And the next question: Will they do it again?
I think it is a bad workaround to re-issue all certificates and delete the old Intermediate CA, just because one certificate uses the new CA.
Thanks for all the good info!

**Comment by ebekker** [comment] 2016-06-18 11:48
I'm hoping this was just a one-time thing justified because LE was still in Beta.

Hopefully going forward they won't reuse the key identifiers.  We have a workable solution for all the pre-existing users from the beta period, and hopefully everyone will be moved over to the new intermediate CA cert over the course of the 3 months (the expiration period of the issued server certs), so I'm closing this issue out for now.

**Closed by ebekker** 2016-06-18 11:48 UTC

**Comment by nul800sebastiaan** [comment] 2016-08-18 10:37
FYI: For me the fix was here: https://social.technet.microsoft.com/Forums/en-US/9cd5d6c8-25e5-494d-acf2-d94230e68a9f/iis-85-on-windows-2012-r2-returns-the-incorrect-intermediate-certificate?forum=winserver8gen#7f00eced-a6b5-4bc1-9303-683ac4e5fc6e

Deleting these registry keys and re-binding the certs to the domains fixed the problem.
