### ISSUE TITLE
Feedback - suggestions

### ISSUE THREAD

**Issue by kniv** [ebekker/ACMESharp#37] opened 2015-11-27 06:09 UTC
Your Example-Usage Wiki [at https://github.com/ebekker/ACMESharp/wiki/Example-Usage] has `Import-Module ACMEPowerShell` as almost the first step.  Many PowerShell admins will assume that this should work after downloading your git project.  It took me a while to find the other url where "artifacts" can be downloaded that include a working .dll.  Suggest adding instructions for PowerShell users who do not have a Visual Studio background on where they can download a compiled package so that the command `Import-Module ACMEPowerShell` works. 

Please provide more detailed help output when running `help *command* -full` from a PowerShell console.  

Running `Initialize-ACMEVault` with the '-verbose' parameter does not output any verbose information.  Suggest adding at least one verbose message in there so users feel comforted.

Running `New-ACMERegistration` with the `-verbose` parameter does not output any verbose information.  Suggest adding at least one verbose message in there so users feel comforted.

Running `New-ACMERegistration` and providing random characters for the `-contacts` parameter results in a generic 'Unexpected error'. Suggest providing examples of formats that the contacts parameter accepts in the error output. 

Running `New-ACMERegistration` and providing a valid `-contacts mailto:xxx@xxx.com` parameter initially resulted in a `New-ACMERegistration : Unexpected error` message for me.  I had to resort to installing Fiddler in order to capture https traffic to determine that the error returned by the ACME server was actually `detail=Error creating new registration :: Validation of contact mailto:xxx@xxx.com failed: Server failure at resolver`.  Please consider echoing the error message returned by the ACME server to the powershell error message. I was able to continue by using a different e-mail address.

Running commands such as `New-ACMERegistration` and `Get-ACMEIdentifier` when the current directory is not `c:\Vault` results in the following error message `New-ACMERegistration : Vault root path does not contain vault data`.   Can that be changed to be something like `Current directory does not contain vault data, please change into a vault directory or specify a vault directory with -VaultProfile`

The wiki appears to skip a few steps in the 'Defining Providers' section.  The line `Submit-ACMEChallenge -Ref dns1 -Challenge http-01` mentions '-Challenge http-01' but the identifier 'http-01' is not mentioned ahead of time.  Not sure where you got that from.  

Also, I personally would love an example of how to perform a 'manualDnsProvider' process.  The json that pops up when I run `New-ACMEProviderConfig -DnsProvider Manual` is fairly basic and doesn't hint at what I should do next.   (also, running `New-ACMEProviderConfig -verbose` doesn't output any verbose messages :) )

That's as far as I got tonight. Thank you for reading this report.

**Comment by ebekker** [comment] 2015-11-27 12:10
Great ideas!  Let me know if you want to work on any of them.

Some of the issue is that the example usage was thrown together with a very early version of the project, before some changes in the official ACME spec and before recent *renovations* in this project, so it needs to be cleaned up and updated.  Once I address some other *foundational* features in the project, then I'll go back and work on the docs.

**Comment by kniv** [comment] 2015-12-03 16:36
I'm not much of a C# developer so I don't know how helpful I would be looking at the source code.  If you have any pure PowerShell stuff I'd be happy to take a look at it.

I figure with the Open Beta coming soon that there will be more windows admins looking for a PowerShell interface to Let's Encrypt, and your project seems to be the only one out there (congrats!).

**Comment by ebekker** [comment] 2016-01-13 04:27
@kniv, with the latest release, v0.8.0.0, a lot of updates and changes have been implemented, and I hope have addressed your concerns.  Please review the release and give me your thoughts.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.

I'm closing this for now, but if you still have concerns, reopen and let's discuss, or you can open new tickets for specific issues.

**Closed by ebekker** 2016-01-13 04:27 UTC
Labels: client-posh, docs, enhancement, help wanted, request
