### ISSUE TITLE
Three challenges after issuing Complete-ACMEChallenge command

### ISSUE THREAD

**Issue by bseddon** [ebekker/ACMESharp#78] opened 2016-01-23 15:40 UTC
I don't think GitHub has a place to provide a pat on the back message so here's mine.  Well done, ACMESharp and the PowerShell support has worked like a charm so far.  But I have a question.

When request an update using the cmdlet Update-ACMEIdentifier I get a response like this - you can see it's pending:

```
IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : wordpress.wproute.com
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/fYH0t_PLtx9c7UGEB9_qaOGQXal4LcsOaLp0GEDBNPg
Status         : pending
Expires        : 1/30/2016 1:08:07 PM
Challenges     : {, manual, }
Combinations   : {2, 0, 1}
```

I waited for ages and tried again.  Same thing.  I thought I'd play with the response to see what information is contains and when I listed the challenges, it turns out there are three and one of them, the one with the token I used for verification, has a status of 'valid'.

Is it normal that there are multiple challenges?  See the challenges listed below.

```

ChallengePart          : ACMESharp.Messages.ChallengePart
Challenge              : 
Type                   : tls-sni-01
Uri                    : https://acme-v01.api.letsencrypt.org/acme/challenge/fYH0t_PLtx9c7UGEB9_qaOGQXal4LcsOaLp0GEDBNPg/10373686
Token                  : G2Obu3Xtyd-yXD4766enNkTAjEofZbZrbbz1Rw-1rU0
Status                 : pending
OldChallengeAnswer     : [, ]
ChallengeAnswerMessage : 
HandlerName            : 
HandlerHandleDate      : 
HandlerCleanUpDate     : 
SubmitDate             : 
SubmitResponse         : 

ChallengePart          : ACMESharp.Messages.ChallengePart
Challenge              : ACMESharp.ACME.HttpChallenge
Type                   : http-01
Uri                    : https://acme-v01.api.letsencrypt.org/acme/challenge/fYH0t_PLtx9c7UGEB9_qaOGQXal4LcsOaLp0GEDBNPg/10373687
Token                  : _F1nNmKkYkzu5qgYP4mRypa0V3Mv0uPPW6Rx-3J8cuo
Status                 : valid
OldChallengeAnswer     : [, ]
ChallengeAnswerMessage : 
HandlerName            : manual
HandlerHandleDate      : 1/23/2016 1:13:24 PM
HandlerCleanUpDate     : 
SubmitDate             : 1/23/2016 1:28:58 PM
SubmitResponse         : {StatusCode, Headers, Links, RawContent...}

ChallengePart          : ACMESharp.Messages.ChallengePart
Challenge              : 
Type                   : dns-01
Uri                    : https://acme-v01.api.letsencrypt.org/acme/challenge/fYH0t_PLtx9c7UGEB9_qaOGQXal4LcsOaLp0GEDBNPg/10373688
Token                  : 6QqNGjk4EeZVPWwb9LJB-MbqpmEqVvoF6tZP1o_I1S0
Status                 : pending
OldChallengeAnswer     : [, ]
ChallengeAnswerMessage : 
HandlerName            : 
HandlerHandleDate      : 
HandlerCleanUpDate     : 
SubmitDate             : 
SubmitResponse         : 
```

**Comment by ebekker** [comment] 2016-01-25 13:44
Thanks for the pat on the back!

Yes, the number of Challenges depends on how many are issued by the ACME Server CA, and LE's server is issuing 3 at the moment (HTTP, TLS-SNI and DNS).  They also issue a list of combinations, so some CA's may require that you complete some combination of the Challenges issued before the Identifier is considered valid as a whole.

Having said that, there is a bug that needs to be corrects where the status of individual Challenges is not properly updated when you refresh the status of an Identifier, see #72.

**Comment by ebekker** [comment] 2016-01-25 13:45
I'm going to close this ticket as I believe the crux of the problem is a duplicate of #72, if you feel that's not the case and this is something different, reopen and provide some details.

**Closed by ebekker** 2016-01-25 13:45 UTC

**Comment by bseddon** [comment] 2016-01-25 17:57
Hi Eugene, I'm not sure it is.  The summary appears to show only the status of the first of the challenges.  In my case the status of the challenges is correct.  However the fact that the status one of the challenges is valid (the second one in the list) is not reflected in the summary. It seems appropriate that summary show valid (or invalid) if any one of the challenges has this state.

I'm over this now and I verify the status by looking at each one:

(Get-ACMEIdentifier $alias).Challenges | Where-Object { $_.Status -eq 'valid' -or $_.status -eq 'invalid' }

But it confused me initially.
