### ISSUE TITLE
Cmdlet Get-Certificate conflicts with built-in commands

### ISSUE THREAD

**Issue by chenrylee** [ebekker/ACMESharp#224] opened 2017-02-20 05:05 UTC
When I tried to install this module, I got this error:
`PackageManagement\Install-Package : The following commands are already available on this system:'Get-Certificate'. This  module 'ACMESharp' may override the existing commands. If you still want to install this module 'ACMESharp', use -Allo wClobber parameter.`

I runs _Powershell 5.1.15031.0_ on _Windows 10.0.15031.0_
![snap00102](https://cloud.githubusercontent.com/assets/10664121/23112415/1d210a12-f76b-11e6-9ca7-1f2e24d6c5b6.png)

**Comment by fpeterson194** [comment] 2017-02-20 17:17
@chenrylee I experienced this error before. This happends due to you already have a function in powershell called Get-Certificate. However, the ACMESharp Get-Certificate function has the string ACME on it. So, you will have no issues/overrights if you put the -AllowClobber parameter. It will work.
Hope this helps.

**Comment by WallyRanson** [comment] 2017-02-20 21:35
If you look in the XML file then you can see it listed as Get-Certificate.
Also on another issue is that it is only version 0.8.1 that available and not the newest 0.8.2.

**Comment by fpeterson194** [comment] 2017-02-23 12:59
@WallyRanson I didn´t find the 0.8.2 version in the download section. In powershell gallery is the 0.8.1. You mean this one: https://www.myget.org/feed/acmesharp-posh-staging/package/nuget/ACMESharp
If it is there it means it is still beta right?

**Comment by WallyRanson** [comment] 2017-02-23 16:46
That is what I am a bit confused about, because in the WIKI section 1 it sounds like 0.8.2 is the current one.

**Comment by ebekker** [comment] 2017-02-24 19:16
The issue is the same in 0.8.1 and 0.8.2.  The PowerShell module defines a `DefaultCommandPrefix` of `ACMES` in its [module manifest](https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.POSH/ACMESharp.psd1) which automatically gets pre-pended to the noun component of each cmdlet that is exported by the module.

The PowerShell "safety mechanisms" do not take this into consideration when comparing the names of module cmdlets with what's already loaded in the current PowerShell session.  Because of this, if you force the clobber, it actually won't actually do anything to your built-in `Get-Certificate` cmdlet.

For the record -- my Get-Certificate (aka Get-ACMECertificate) came first, before PowerShell 5 added theirs.  Also, you can force or override the default prefix using the `-Prefix` parameter to the `ipmo` call to be sure no module overrides what's already in your session.

**Comment by ebekker** [comment] 2017-04-11 22:04
Duplicate of #159 and #168.

**Closed** 2017-04-11 22:05 UTC
Labels: docs-faq, duplicate

**Comment by ebekker** [comment] 2017-08-23 03:18
See [this article](https://pkisharp.github.io/ACMESharp-docs/Why-AllowClobber) for details about this issue.
