### ISSUE TITLE
Errors while compiling current version

### ISSUE THREAD

**Issue by Wilmaro** [ebekker/ACMESharp#178] opened 2016-11-04 14:03 UTC
Hi,

I get several errors when I try to compile the current version. Am I missing a reference?

Example:
Error	79	'ACMESharp.Messages.ChallengeAnswerRequest._fieldValues' is a 'field' but is used like a 'type'	ACMESharp-master\ACMESharp-master\ACMESharp\ACMESharp\Messages\ChallengeAnswerRequest.cs	51	20	ACMESharp

```
int IReadOnlyCollection<KeyValuePair<string, object>>.Count
                => _fieldValues.Count;
```

**Comment by ebekker** [comment] 2016-11-04 16:39
You're using VS2015, correct?  There should be any missing references, otherwise I imagine the [AppVeyor builds](https://ci.appveyor.com/project/ebekker/acmesharp) would be breaking too.

Did you just clone the repo to your local host or did you pull down a zip archive of the source?

**Comment by ebekker** [comment] 2016-11-04 16:40
Are all the errors of this same type?  e.g. X is a 'field' but is used like a 'type'

**Comment by Wilmaro** [comment] 2016-11-04 23:29
Hi, I downloaded a zip. Im using visual studio 2013.

Met vriendelijke groeten/Kind regards,

Wilmaro Zimmerman

**Comment by Wilmaro** [comment] 2016-11-04 23:30
Yes, all are the same

Met vriendelijke groeten/Kind regards,

Wilmaro Zimmerman

**Comment by ebekker** [comment] 2016-11-05 22:09
Ah, the problem is pby due to your using Visual Studio 2013.  I developed ACMESharp in Visual Studio 2015, and made use of C# 6.0 features liberally, so there is much (most?) of the code base which will not compile in your environment.

Now VS2015 is available as a free Community Edition, which is what I use, so you can install it side-by-side in your environment (assuming you have the disk space).

I looked into what support there is for C# 6.0 in VS2013, and I'm seeing mixed results, so YMMV:
* [supposedly no support](https://social.msdn.microsoft.com/Forums/en-US/49ba9a67-d26a-4b21-80ef-caeb081b878e/will-c-60-ever-be-supported-by-vs-2013?forum=roslyn)
* [possibly some support, but maybe outdated](http://stackoverflow.com/a/27093973/5428506)

**Comment by Wilmaro** [comment] 2016-11-05 22:36
Ah thanks a lot for your reply. I have visual studio 2015 too, I opened it in 2013 as I'm still developping mainly in 2013. I'll open it in 2015. Thanks again

Met vriendelijke groeten/Kind regards,

Wilmaro Zimmerman

**Comment by ebekker** [comment] 2016-11-07 13:20
Cool, please close the issue once you verify this is working in VS2015.

**Comment by Wilmaro** [comment] 2016-11-08 00:25
Thanks for the help ebekker

**Closed** 2016-11-08 00:25 UTC
