### ISSUE TITLE
Submit-ACMEChallenge : Unable to update challenge :: Challenge data was corrupted

### ISSUE THREAD

**Issue by zawsx** [ebekker/ACMESharp#120] opened 2016-04-08 21:26 UTC
First tried DNS challenge but Cloudfare would not accept: 
_acme-challenge.www.example.com 
as the txt record name - keeps truncating it to:
_acme-challenge.www

Filed a support ticket with cloudfare.

So I switched to the http method:
**Submit-ACMEChallenge dns1 -ChallengeType http-01**

where **dns1** is www.example.com

Produced this red text:

Submit-ACMEChallenge : Unable to update challenge :: Challenge data was corrupted
At line:1 char:1
- Submit-ACMEChallenge dns1 -ChallengeType http-01
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (ACMESharp.Vault.Model.IdentifierInfo:IdentifierInfo) [Submit-ACMEChallenge
    ], AcmeWebException
  - FullyQualifiedErrorId : urn:acme:error:malformed (400),ACMESharp.POSH.SubmitChallenge

I then tried to create a cert for the apex:
**Submit-ACMEChallenge dns2 -ChallengeType http-01**
where **dns2** is example.com

That works fine with the http method.

I read that, if you try both dns and http methods, this error happens - is that true?
Also read about mime types, mine are text/plain and, as example.com verifies, so that can't be it.
Is there a way to delete both www.example.com challenges and start again?

**Comment by bseddon** [comment] 2016-04-11 13:35
The issue is that you are using the same alias (dns1 in your example).  The alias represents a copiy of data from the Let's Encrypt servers held by ACMESharp in the vault.  When you ran the command Submit-ACMEChallenge for the DNS request you 'consumed' that alias.  Later you tried to reuse that alias but for a different challenge type.  Let's Encrypt reports this as corrupted data - which it is because the keys have changed.

The second use of the Submit-ACMEChallenge command worked because you also used a different alias.

So in some sense it is true that you will see an error if you use both dns and http but that's not really an adequate description of the issue.

**Comment by zawsx** [comment] 2016-04-11 14:47
Thanks for taking the time to explain - really appreciate it. 

It's not a bug then but maybe it's worth the client highlighting the error trap, as you say, using the same alias for two different challenge types is illegal and defeated me, idiot that I am.

Something like 'each challenge type on the same domain requires a unique alias'
Or maybe if the client auto-appended the challenge-type internally to the alias, as in dns1-http01 or somesuch?

Thanks again.

**Comment by bseddon** [comment] 2016-04-11 15:38
I'm sure @ebekker will consider your suggestion.  It may be difficult to do much about the message in terms of outputting a more intelligible response. The message is generated by the Let's Encrypt servers which reports the same message for a range of issues related to the validation of an identifier.  For example, if the file you create for the HTTP challenge response has been saved using unicode or if there is line end character on the end of the token in the file it will report the same problem.

In the meantime, you are able to test whether the alias has been used using the Get-ACMEIdentifier command.  If any one of the challenges returned by this command has a status of 'valid', 'invalid' or 'pending' you know it cannot be used again.

Others have suggested that is be possible to remove or reassign existing aliases and #118 has been created to track this suggestion.

**Comment by ebekker** [comment] 2016-04-20 20:47
The issue here is that the Challenge is not necessarily specific to a single Challenge Type -- for example the ACME protocol allows for an ACME server to *require* that an account prove ownership of a DNS Identifier using 2 or more different types, so the whole auto-appending thing is not very scalable in that approach.

However, I think it's easy enough to inspect the current status of all of the different Challenge Types on a given Challenge, and if any of them have failed, then it's pby safe to warn the user not to use that Challenge at all.

The other issue is that there is a bug as described in #90, where the *overall* Challenge status is not being properly updated from the LE server.  If that were working correctly, it would have shown that the Challenge has already failed after the first Challenge type failed, and it would not be possible to continue without re-requesting a new Authorization.

**Comment by zawsx** [comment] 2016-04-20 21:05
Thanks for looking at this - I appreciate the care and attention to detail you've shown - the true mark of genius :)
The more bulletproof the client is, the more idiot proof against those like me :)

**Closed** 2016-11-12 21:52 UTC

**Comment by ebekker** [comment] 2016-11-12 22:23
I've added status checks in the `Complete-ACMEChallenge` and `Submit-ACMEChallenge` cmdlets to make sure the overall Identifier authorization is still in a `pending` state and that no challenges are in an `invalid` state, otherwise an exception is thrown for an invalid state.

These validations can be overridden by simply passing the `-Force` flag to these two cmdlets.
