### ISSUE TITLE
Status stuck on "invalid"

### ISSUE THREAD

**Issue by christopherjamesgunn** [ebekker/ACMESharp#105] opened 2016-03-03 20:23 UTC
IdentifierPart : ACMESharp.
IdentifierType : dns
Identifier     : .........
Uri            : .........
Status         : invalid
Expires        : 10/03/2016
Challenges     : {, manual,
Combinations   : {1, 0, 2}

Hi all I can't seem to get past the validation stage of "invalid" can anyone help?

I attempted the http challenge,

However I didn't know how to setup the dns challenge

Many thanks

Chris

**Comment by bseddon** [comment] 2016-03-04 08:32
Once an identifier is invalid, you have to create a new identifier.  There's no limit to the number of identifiers you can create, you just need to use a unique alias for each one.

I'm not sure what you mean by the comment 'I didn't know how to setup the dns challenge'.  Have you been through steps 4 to 6b on the [Quick Start page](https://github.com/ebekker/ACMESharp/wiki/Quick-Start)?

**Comment by christopherjamesgunn** [comment] 2016-03-04 08:47
Hi,

Thank you for responding

I'm unsure how to recreate a new unique alias?

I used the domain let's say www.example.com

I can't reuse the same domain using the same method on the QuickStart page

In terms of the DNS, I'm unsure where the place the verification needed? I
have a DNS server setup on my domain controller do I place it there, or do
I need to input this code on my domain registrar?

**Comment by bseddon** [comment] 2016-03-04 09:08
Step 4 of the quick start guide suggests this command:

New-ACMEIdentifier -Dns myserver.example.com -Alias dns1

The alias used in this command is 'dns1'.  It could have been 'dns2' or 'xyz' or anything else.  The domain, 'myserver.example.com' in the example above or 'www.example.com' in your comment, can be reused with any number of different aliases.  In fact it is necessary to regenerate certificates every 60 days so being able to use a new alias is an essential part of the process.  

I use a date to generate unique aliases so for me the example from the quick start guide will be:

New-ACMEIdentifier -Dns myserver.example.com -Alias dns1-2016-03-03

It's harder to give you a definitive answer to your question about the DNS settings because I don't know how your DNS servers are configured.  My guess is that It's unlikely to be the domain name server on your domain controller unless that is visible to the wider internet network and is the authoritative name server for the domain you want to validate.  Unusually domain controllers are hidden behind a firewall and are there to serve the name resolution needs of machines in the local domain. 

If you use the DNS validation (method #2 in the quick start) the Let's Encrypt servers have to be able to access the authoritative domain name server for the domain being validated.  It is likely that the domain server for www.example.com is hosted by a registrar in which case it is to the registrar's server that the TXT record containing the challenge token should be added.

Hope that helps.

**Comment by christopherjamesgunn** [comment] 2016-03-04 09:42
Hi thanks for this,

I'm going to try this now.

I have one more question if that's okay

I've setup a new identifier and I've decided to complete the http
challenge. What format do I need to provide the challenge token?

So for example would it be .well-known/acme-challenge/filepath.txt

Or /filepath(as a folder)/file.txt

Many thanks

**Comment by bseddon** [comment] 2016-03-04 10:02
It will be the exact path returned when your run the Complete-ACMEChallenge command.  Here's result shown in the example from the quick start:

```
== Manual Challenge Handler - HTTP ==
  * Handle Time:      [1/12/2016 1:16:34 PM]
  * Challenge Token:  [2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0]
To complete this Challenge please create a new file
under the server that is responding to the hostname
and path given with the following characteristics:
  * HTTP URL:     [http://myserver.example.com/.well-known/acme-challenge/2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0]
  * File Path:    [.well-known/acme-challenge/2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0]
  * File Content: [2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0.H3URk7qFUvhyYzqJySfc9eM25RTDN7bN4pwil37Rgms]
  * MIME Type:    [text/plain]
```

In this example, the LE servers will attempt to access the resource (HTTP URL):

http://myserver.example.com/.well-known/acme-challenge/2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0

This resource will contain the contain the characters (File Content):

```
2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0.H3URk7qFUvhyYzqJySfc9eM25RTDN7bN4pwil37Rgms
```

Do not use unicode and do not include a carriage return at the end of the line.  If you are using IIS you will need to setup a mime definition with no extension that uses 'text/plain' as the type or IIS will report a 403 error.

**Comment by christopherjamesgunn** [comment] 2016-03-04 11:05
Hi again,

HTTP verification complete.

Just needing to the DNS one now as well as it's wanting me to to do multiple.

I use 1and1 as a registrar for my domain.

When I come to add the txt file to my records.

I go to add the Prefix "_acme-challenge" but it doesn't allow me.

Even though the name underneath prefills with _acme-challenge.www.domainname.com

The error message shows:
Enter a string matching the following regular expression: ^_?[0-9a-zA-Z-+*]+._[0-9a-zA-Z-]+$. Example: selector._domainKey or _selector._domainKey

Many thanks for all your help on this

**Comment by bseddon** [comment] 2016-03-04 11:47
There is a standard for what information can be held in DNS records but no standard for how the owner of a nameserver will allow you to create and enter values into records.

The regular expression indicates that your provider is expecting you to enter a name in the format 

something<dot>something

This is the format needed when you are entering a DKIM public key but is not much use for you entering a record for the LE servers to find.  You will need to ask 1&1 how you are able to enter a name in the form required by Let's Encrypt.

**Comment by ebekker** [comment] 2016-03-26 10:40
It looks like your provider doesn't allow you to enter a value that is required for the LE servers to authenticate the record.  You can submit a request to have them look at this use case, but otherwise, there's not much you can do other than switch DNS providers.

It looks like this issues has been resolved as far as we can go, so I'm closing for now.

**Closed by ebekker** 2016-03-26 10:40 UTC

**Comment by christopherjamesgunn** [comment] 2016-03-26 10:57
Hi Eugene ,

Can you recommend a provider that will allow these kind of requests?

Many thanks

C

**Comment by ronpsych** [comment] 2016-07-18 21:58
hi also ecountering this error, i use method 3 and stuck on 6b
IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : md***.csc-fsg.com (i censored the dns)
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/0KhHxMLKkAcEfQv911Iw2GnXbdbo19EN0tVCOOMmDtY
Status         : pending
Expires        : 7/25/2016 9:15:46 PM
Challenges     : {, manual, }
Combinations   : {2, 0, 1}

**Comment by bseddon** [comment] 2016-07-18 22:19
If you follow the link you have provided in you comment:

https://acme-v01.api.letsencrypt.org/acme/challenge/0KhHxMLKkAcEfQv911Iw2GnXbdbo19EN0tVCOOMmDtY/182916109

you will see the Let's Encrypt servers are unable to resolve the required domain:

_acme-challenge.mdwdevalwa.csc-fsg.com

This domain does not exist so you cannot complete the challenge.  If you are going to use the DNS challenge method you need to make sure this TXT record exists in your DNS records before you attempt to submit.  The content of the TXT record should be the 'token'.

**Comment by ronpsych** [comment] 2016-07-19 13:30
Will a FW Rules affecting this issue? We just only had this url https://acme-v01.api.letsencrypt.org bypass via proxy and a FW rules was not in place. Also IP for the URL is changing/elastic I might have problem getting it approved. Please advise.

**Comment by bseddon** [comment] 2016-07-19 13:40
The issue you have reported is a consequence of not having the correct records in your DNS server.  Proxy server and firewall rules are not going to affect the ability of the outside world to discover these DNS records.

Although you have used the DNS challenge method, maybe you did not mean to use it.  If the letsencrypt.org servers are now able to access your web server have you tried using the http challenge method?

**Comment by ronpsych** [comment] 2016-07-19 14:02
will try that though. Thanks for the information. I will give you a feedback.

**Comment by ronpsych** [comment] 2016-07-19 14:26
here is the new error:

PS C:\Users\appsu> Complete-ACMEChallenge dns1_0719 -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef
 = 'mdwdevalwa.csc-fsg.com' }
Complete-ACMEChallenge : The given key was not present in the dictionary.
At line:1 char:1
+ Complete-ACMEChallenge dns1_0719 -ChallengeType http-01 -Handler iis -HandlerPar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,ACMESharp.POSH.CompleteChallenge

**Comment by ronpsych** [comment] 2016-07-19 14:52
hi just an update I had past this and, found new error below. Please be reminded that we call the website via 443/https, i guess that is the reason why it is not resolving.

  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to http://mdwdevalwa.csc-fsg.com/.well-known/acme-challenge/fBQDAQM71ziBp1zs8woAYtpkil249mbk6AerFGN383I",
    "status": 400

**Comment by bseddon** [comment] 2016-07-19 15:47
Yes.  Let's Encrypt requires the challenge is from their server to an http address on your server.

I imagine this is why you started using the DNS challenge method.  But to use the DNS method you have to be able to update the DNS server records.  If there are only a few people able in your organization who are are authorized change firewall settings, it is likely there are even fewer who are authorized to change DNS records.

**Comment by ronpsych** [comment] 2016-07-19 15:55
thanks, bseddon, really appreciate your help. Any advise we can use this tool?

**Comment by bseddon** [comment] 2016-07-19 16:03
The issue is not the tool, its Let's Encrypt.  Let's Encrypt controls the ways in which it will conduct challenges.  It may be that you are unable to use certificates from Let's Encrypt.

If you have a site that is able to respond to a request on port 80 then it should be possible for you to complete the challenge if port 80 is opened on your firewall.  However, just because the port can be accessed it does not mean there is a web server listen on that port waiting to respond.  All the pieces have to be in place.

**Comment by ronpsych** [comment] 2016-07-19 16:23
okay, thanks we will work with FW Rules. Does this need to be open on internet?

**Comment by bseddon** [comment] 2016-07-19 17:55
It has to be accessible by the Let's Encrypt servers.  It has to be possible for their servers are able to access the file you create on your web server listening on port 80 via the path specified by them when you issue the 'New-ACMEIdentifier' command.  It doesn't matter that I or anyone else cannot access your web site but their servers must be able to do so.

**Comment by ronpsych** [comment] 2016-07-19 18:56
thank you. very much appreciated.

**Comment by ronpsych** [comment] 2016-07-20 15:41
hi chief, just an update.. we have open the FW Rules from internet going to our server and opening port 80...
 
i got this new error:

     "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://mdwdevalwa.csc-fsg.com/.well-known/acme-challenge/Pd6BHEtk1sOmVg7HjCxZJ5IqguoSiFjguuu_hLhwzxI: \"\u003c!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\"\u003e\r\n\u003chtml xmlns=\"http\"",
        "status": 403

**Comment by bseddon** [comment] 2016-07-20 16:12
If I [visit the link](http://mdwdevalwa.csc-fsg.com/.well-known/acme-challenge/Pd6BHEtk1sOmVg7HjCxZJ5IqguoSiFjguuu_hLhwzxI) the Let's Encrypt servers are going to visit to complete the challenge I also see a 403 error.  Do you see a 403 error visiting this page?

Maybe you are inside the firewall so see different responses.  Anyway, the LE servers are receiving a 403 status code so you need to resolve this on your server.

**Comment by ronpsych** [comment] 2016-07-20 17:11
hi yes, I saw this. can you educate me which file on the server they are accessing?

**Comment by bseddon** [comment] 2016-07-20 18:53
When you issue a New-ACMEIdentifier command you are presented with the name of the file the Let's Encrypt servers require that you create and the content it must contain.

You can recover this information any time by running a PoweShell command like:

```
((Get-ACMEIdentifier your-alias.Challenges | Where-Object { $_.type -eq 'http-01' }).Challenge
```
This command will return the file name the Let's Encrypt servers expect to find and the content of that file.  The output of this command (using one of my aliases) for one of my old certificates is:

```
Token       : 4TMiHvGZisXE5QT7lNGobQLDIoo516MOKPDHzyptLKc
FileUrl     : http://wordpress.wproute.com/.well-known/acme-challenge/4TMiHvGZisXE5QT7lNGobQLDIoo516MOKPDHzyptLKc
FilePath    : .well-known/acme-challenge/4TMiHvGZisXE5QT7lNGobQLDIoo516MOKPDHzyptLKc
FileContent : 4TMiHvGZisXE5QT7lNGobQLDIoo516MOKPDHzyptLKc.n14-BcGUXDoHA7gxo5pBeDrZsdq1IwwLnSHuw0yVPP8
TypeKind    : HTTP
Type        : http-01
```

The FileUrl is the path and file you are expected to create and FileContent is the content for that file (the content MUST NOT include a carriage return at the end).

Hope this helps.

**Comment by ronpsych** [comment] 2016-07-20 21:55
Thanks, is file path something visible on server side?

**Comment by bseddon** [comment] 2016-07-20 22:25
If you are unsure, it's really a question for your web server administrator because the answer to your question depends upon the web server you are using, the configuration of that web server, etc. 

In my case the URL:

http://wordpress.wproute.com/.well-known/acme-challenge/4TMiHvGZisXE5QT7lNGobQLDIoo516MOKPDHzyptLKc

resolves to a file the contents of which are returned by my web server.  The specific location on the mounted hard drive, and so the location of the file, depends upon the definition of the virtual folder hosting the static files for the web site.

**Comment by ronpsych** [comment] 2016-07-21 13:55
hi, quick question. is one of the reason why I am not succeeding is that. Upon registration I should be able to receive and email from letsencrypt? in my case I did not receive any,

**Comment by bseddon** [comment] 2016-07-21 14:03
No. The email entered during registration is not used.

The reason you are not succeeding is because your web server environment is not configured in a way that will permit the Let's Encrypt servers validate your request.

**Comment by bseddon** [comment] 2016-07-21 14:06
It's not used during the certificate creation process.  Let's Encrypt do use the email address to send out reminders when certificates are due expire.

**Comment by ronpsych** [comment] 2016-07-21 14:20
Thank, I am looking on web server access rights. because when I try to hit this page 
https://acme-v01.api.letsencrypt.org/acme/challenge/sk1c6hEI6ahywUDNMYm5WThvBJs1XD-dEOjkmfjj4-w/188123537
the server wont allow me to download it.

![image](https://cloud.githubusercontent.com/assets/20525436/17026027/38a6641c-4f91-11e6-8fb5-3003cb32c2e6.png)

please advise. I appreciate your help so much.

**Comment by bseddon** [comment] 2016-07-21 14:22
I think you have problems with your firewall or proxy.  When I visit the page included in your last post I see the following (which is what I would expect to see):

```
{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",
    "detail": "Invalid response from http://mdwqatalwa.csc-fsg.com/.well-known/acme-challenge/l5pvePFzGKOiev5GdqBHZQU1gDSl20EdjseRMcs9zzw: \"\u003c!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\"\u003e\r\n\u003cHTML\u003e\u003cHEAD\u003e\u003cTITLE\u003eNot Found\u003c/TITLE\u003e\r\"",
    "status": 403
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/sk1c6hEI6ahywUDNMYm5WThvBJs1XD-dEOjkmfjj4-w/188123537",
  "token": "l5pvePFzGKOiev5GdqBHZQU1gDSl20EdjseRMcs9zzw",
  "keyAuthorization": "l5pvePFzGKOiev5GdqBHZQU1gDSl20EdjseRMcs9zzw.7voixubb8rEoAkwnhVKIsIuUK2ZkiBxf1gdmrTAw6FA",
  "validationRecord": [
    {
      "url": "http://mdwqatalwa.csc-fsg.com/.well-known/acme-challenge/l5pvePFzGKOiev5GdqBHZQU1gDSl20EdjseRMcs9zzw",
      "hostname": "mdwqatalwa.csc-fsg.com",
      "port": "80",
      "addressesResolved": [
        "170.30.214.196"
      ],
      "addressUsed": "170.30.214.196"
    }
  ]
}
```

**Comment by ronpsych** [comment] 2016-07-21 14:32
Thats maybe the case but as per FW team they dont see anything that was blocked from letsencrypt.org. also, on this phase of installation.. should i do this manually?

![image](https://cloud.githubusercontent.com/assets/20525436/17026520/e4a13444-4f92-11e6-9e8a-1ee94b263484.png)

if yes, where in particular? IIS websites? then create new application/directory? 

thank you so much for your help, this is a guinea pig in the company if I got this working we can have this as an option on other lower env...

**Comment by bseddon** [comment] 2016-07-21 14:40
The Let's Encrypt servers are working correctly.  I don't have a problem accessing your information on their servers but you do.  That means, whether your firewall administrators are prepared to concede the point or not, the issue is within your organization.

I'm sorry you find yourself in the middle.  However, this is not a forum in which to try to educate someone how to have a site hosted by IIS serve a file.  At least, it's not something I want to get into.  Perhaps others will pick up the challenge.  In the meantime, there are many resources on the Microsoft web site that will allow you to learn to answer your own questions.
