### ISSUE TITLE
Update-ACMEIdentifier command removes the challenge?

### ISSUE THREAD

**Issue by hlicityview** [ebekker/ACMESharp#91] opened 2016-02-11 17:46 UTC
Hi there, 

I run into an awkward situation, I'm using the manual dns-01 challenge, and before I submit the challenge, I run the command "Update-ACMEIdentifier MyAliasName", without define the "-ChallengeType dns-01" part, to checkout the status. The output shows there are no challenges anymore, so when I try to "Submit-ACMEChallenge MyAliasName -ChallengeType dns-01", the output returns the "Submit-ACMEChallenge : challenge has not been decoded" error.

I tried with couple of test, it seems that "Update-ACMEIdentifier MyAliasName -ChallengeType dns-01" will keep the challenge on record, but "Update-ACMEIdentifier MyAliasName" will definitely remove the challenge somehow.

Just wondering if this is an ACMESharp issue or let's encrypt server issue? Is there a way to fix the identifier?

**Comment by bseddon** [comment] 2016-02-11 20:02
You will be able to go some way to answering your own question.  When you issue the command:

Get-ACMEIdentifier MyAliasName

It will include in the return a uri.  The uri is to the information about your identifer/challenges on the LE servers.  You can use the uri to find out the state of your identifier/challenges on the LE servers.  The information shown when you use the uri is in JSON format.  The purpose of the ACME update command is to pull this JSON so maybe they should be in sync.

**Comment by ebekker** [comment] 2016-02-22 14:53
Hmm, very peculiar, possibly a bug or you caught LE in the middle of a release update.  The issue could potentially be on either end (LE or ACMESharp).

Did you by any chance try @bseddon 's suggestion?  If so, what was your result?  I'm also curious if you did the update now, if the Challenges would be recovered?

**Comment by hlicityview** [comment] 2016-02-23 00:24
I just went through the code, and seems in AcmeClient.cs, RefreshIdentifierAuthorization() method will wipe out existing challenge authorization state and modify .VAULT file since no "ChallengeType" defined? So I guess either I'm using the Update-ACMEIdentifier command wrong or it is a bug.

Thanks @bseddon, I tried with Get-ACMEIdentifier command, it won't recover the challenge handler since LE doesn't have that piece of information in their JSON data? however, if I don't run Update-ACMEIdentifier first, Get-ACMEIdentifier will not modify the challenge handler or challenge authorization state, so I do have something like "Challenges : {manual, , }" instead of "Challenges: {, , }".

**Comment by bseddon** [comment] 2016-02-23 09:29
Whenever an identifier is created, three challenges are created, one for each of http, dns and tns.  You define which challenge you will use in the Complete-ACMEIdentifier command.  When you finally issue the Submit-ACMEChallenge ACMESharp will use these details to ask the LE servers to initiate the process using the requested method.  The resulting JSON on the LE servers is retrieved and stored in the vault.  Since the domain validation process is asynchronous, by the time the Submit-ACMEChallenge command returns the LE server may not have completed the validation check so it is important to run the command Update-ACMEIdentifier which really just accesses the current state of the JSON.

You can see the JSON on the LE servers for yourself by visiting the uri displayed when you issue the command:

```
Get-ACMEIdentifier <myalias>
```

Are you able to see the page? Does the JSON on the LE server look OK?

In your case, it seems something is not working correctly. Maybe the vault is corrupt?  Have you tried deleting the vault and starting over?

**Comment by ebekker** [comment] 2016-02-23 12:31
@hlicityview, you are correct -- with each update (refresh) of the Identifier Authorization, it is overwriting the current saved state of the Identifier and its Challenges, because when you request the current state of an existing Identifier from the ACME Server (LE), it is supposed to return the *complete* current state, so in theory it should return everything.

As @bseddon suggested, you can go directly to the URL for your Identifier and you should see the current state for yourself as it's represented on the LE server, along with all the Challenge Types and their individual statuses.

If you do this, what do you see?  Do you see all 3 of the original Challenges?

Please note, the `Get-ACMEIdentifier` cmdlet only accesses state as its persisted in the local Vault.  The `Update-ACMEIdentifier` cmdlet will actually go out to the remote ACME Server and retrieve its current state and update the local state in the Vault.

**Comment by hlicityview** [comment] 2016-02-24 21:27
@ebekker, yes I can see all 3 challenges from the LE server response JSON, and they are identical whether my local Vault lost the challenges' state or not. So I'm a bit confused how that authorization state been decoded or retrieved to make my local Vault lost that piece of information.

here is my output step-by-step
![capture](https://cloud.githubusercontent.com/assets/11299323/13301547/612deff6-dafa-11e5-8e5e-ae6cf4b5d05c.PNG)

**Comment by bseddon** [comment] 2016-02-24 22:20
What do you think is wrong?  I have followed the same commands (and the same fake domain name) and I see the same results.  I think this is correct.  The process cannot go any further because you don't own 'domainname.com' so you cannot complete the challenge.

**Comment by hlicityview** [comment] 2016-02-24 22:37
@bseddon, my issue is not to complete the challenge with the given domain.

The difference here is "Update-ACMEIdentifier dns1 -ChallengeType dns-01" cmdlet will retrieve the correct state so you have "Challenges: {manual, ,}" in your output; however, with "Update-ACMEIdentifier dns1" cmdlet, your local state change to "Challenges: {, , }" which makes your later submit challenge step fail with "Submit-ACMEChallenge : challenge has not been decoded" error.

I can create as many New-ACMEIdentifier as I need, and have one of the challenge successfully completed. The problem is that I cannot continue with an existing identifier if the local challenge state lost or Vault corrupted by the Update-ACMEIdentifier cmdlet.

**Comment by bseddon** [comment] 2016-02-25 00:06
I agree. And I can reproduce the same error (even using challenge type http-01). But the problem you are experiencing is because you are running the commands out of sequence.  In the [Quick Start guide](https://github.com/ebekker/ACMESharp/wiki/Quick-Start) the examples correctly show the steps being in the order:

(4) New-ACMEIdentifier
(5) Complete-ACMEChallenge
(6) Submit-ACMEChallenge
(6b) Update-ACMEIdentifier

You are running the commands in the 4,5,6b, 6.  My guess is that the storage of the JSON is not protecting us from running the commands in the wrong order.

If you run them in the wrong order, that is, issue an update command before you issue a submit (and complete the challenge setup) the information one the LE server is not going to be correct. 

There appears to be a difference in the way LE processes dns-01 and http-01. The situation is more clear when using challenge type http-01 as the challenge is invalidated almost straight away.  If you issue an update command for this challenge type before the submit the challenge response returns invalid.  Why there's a difference, I don't know but the difference appears to be in the behavior of the LE servers.

**Comment by ebekker** [comment] 2016-03-26 10:41
@hlicityview, did @bseddon 's suggestion correct your problem?

I'm closing for now, reopen if it's still an issue.

**Closed by ebekker** 2016-03-26 10:41 UTC
Labels: bug, client-lib, question
