### ISSUE TITLE
Identifier valid but Expired authorization

### ISSUE THREAD

**Issue by jmantnz** [ebekker/ACMESharp#213] opened 2017-01-19 09:03 UTC
When i want to renew my certificate, i get the following message:

Update-ACMEIdentifier dns1
Update-ACMEIdentifier : Expired authorization
At line:1 char:1
+ Update-ACMEIdentifier dns1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (ACMESharp.Vault.Model.IdentifierInfo:IdentifierInfo) [Update-ACMEIdentifie
   r], AcmeWebException
    + FullyQualifiedErrorId : urn:acme:error:malformed (404),ACMESharp.POSH.UpdateIdentifier

But when i check whether it's valid or not:

Get-ACMEIdentifier dns1

IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : mail.--------.nl
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/aWFnbq64hUExv3N1gNIs-qGUmc7lHIlV-R-aZlurm-A
Status         : valid
Expires        : 1/9/2017 9:45:01 AM
Challenges     : {, , }
Combinations   : {0, 1, 2}

Can somebody help me with this?

**Comment by ebekker** [comment] 2017-01-19 10:16
Duplicate of #165.  Please see the comments from last few days.

**Closed by ebekker** 2017-01-19 10:16 UTC
